# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 03:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('post_body', models.TextField(verbose_name='Post Body')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('photo_file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
    ]
